// Список таблиц для импорта в правильном порядке (с учетом зависимостей)
const importTables = [
	{
		name: 'setting',
		filename: 'settings.csv',
		hasSequence: true,
		sequenceName: 'setting_setting_id_seq',
		truncate: true,
		excludeColumns: ['setting_id'], // Исключаем автоинкрементные ID
	},
	{
		name: 'category',
		filename: 'categories.csv',
		hasSequence: true,
		sequenceName: 'category_category_id_seq',
		truncate: true,
		excludeColumns: ['category_id'], // Исключаем автоинкрементные ID
	},
	{
		name: 'category_description',
		filename: 'category_descriptions.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['category_description_id'],
	},
	{
		name: 'attribute',
		filename: 'attributes.csv',
		hasSequence: true,
		sequenceName: 'attribute_attribute_id_seq',
		truncate: true,
		excludeColumns: ['attribute_id'],
	},
	{
		name: 'attribute_option',
		filename: 'attribute_options.csv',
		hasSequence: true,
		sequenceName: 'attribute_option_attribute_option_id_seq',
		truncate: true,
		excludeColumns: ['attribute_option_id'],
	},
	{
		name: 'attribute_group',
		filename: 'attribute_groups.csv',
		hasSequence: true,
		sequenceName: 'attribute_group_attribute_group_id_seq',
		truncate: true,
		excludeColumns: ['attribute_group_id'],
	},
	{
		name: 'attribute_group_link',
		filename: 'attribute_group_links.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['attribute_group_link_id'],
	},
	{
		name: 'variant_group',
		filename: 'variant_groups.csv',
		hasSequence: true,
		sequenceName: 'variant_group_variant_group_id_seq',
		truncate: true,
		excludeColumns: ['variant_group_id'],
	},
	{
		name: 'collection',
		filename: 'collections.csv',
		hasSequence: true,
		sequenceName: 'collection_collection_id_seq',
		truncate: true,
		excludeColumns: ['collection_id'],
	},
	{
		name: 'product',
		filename: 'products.csv',
		hasSequence: true,
		sequenceName: 'product_product_id_seq',
		truncate: true,
		excludeColumns: ['product_id'],
	},
	{
		name: 'product_description',
		filename: 'product_descriptions.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['product_description_id'],
	},
	{
		name: 'product_image',
		filename: 'product_images.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['product_image_id'],
	},
	{
		name: 'product_inventory',
		filename: 'product_inventory.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['product_inventory_id'],
	},
	{
		name: 'product_collection',
		filename: 'product_collections.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['product_collection_id'],
	},
	{
		name: 'product_attribute_value_index',
		filename: 'product_attribute_values.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['product_attribute_value_index_id'],
	},
	{
		name: 'product_custom_option',
		filename: 'product_custom_options.csv',
		hasSequence: true,
		sequenceName: 'product_custom_option_product_custom_option_id_seq',
		truncate: true,
		excludeColumns: ['product_custom_option_id'],
	},
	{
		name: 'product_custom_option_value',
		filename: 'product_custom_option_values.csv',
		hasSequence: true,
		sequenceName: 'product_custom_option_value_product_custom_option_value_id_seq',
		truncate: true,
		excludeColumns: ['product_custom_option_value_id'],
	},
	{
		name: 'admin_user',
		filename: 'admin_user.csv',
		hasSequence: true,
		sequenceName: 'admin_user_admin_user_id_seq',
		truncate: true,
		excludeColumns: ['admin_user_id'],
	},
	{
		name: 'cart',
		filename: 'cart.csv',
		hasSequence: true,
		sequenceName: 'cart_cart_id_seq',
		truncate: true,
		excludeColumns: ['cart_id'],
	},
	{
		name: 'cart_address',
		filename: 'cart_address.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['cart_address_id'],
	},
	{
		name: 'cart_item',
		filename: 'cart_item.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['cart_item_id'],
	},
	{
		name: 'cms_page',
		filename: 'cms_page.csv',
		hasSequence: true,
		sequenceName: 'cms_page_cms_page_id_seq',
		truncate: true,
		excludeColumns: ['cms_page_id'],
	},
	{
		name: 'cms_page_description',
		filename: 'cms_page_description.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['cms_page_description_id'],
	},
	{
		name: 'coupon',
		filename: 'coupon.csv',
		hasSequence: true,
		sequenceName: 'coupon_coupon_id_seq',
		truncate: true,
		excludeColumns: ['coupon_id'],
	},
	{
		name: 'customer',
		filename: 'customer.csv',
		hasSequence: true,
		sequenceName: 'customer_customer_id_seq',
		truncate: true,
		excludeColumns: ['customer_id'],
	},
	{
		name: 'customer_address',
		filename: 'customer_address.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['customer_address_id'],
	},
	{
		name: 'customer_group',
		filename: 'customer_group.csv',
		hasSequence: true,
		sequenceName: 'customer_group_customer_group_id_seq',
		truncate: true,
		excludeColumns: ['customer_group_id'],
	},
	{
		name: 'event',
		filename: 'event.csv',
		hasSequence: true,
		sequenceName: 'event_event_id_seq',
		truncate: true,
		excludeColumns: ['event_id'],
	},
	{
		name: 'migration',
		filename: 'migration.csv',
		hasSequence: false,
		excludeColumns: ['migration_id'],
	},
	{
		name: 'order',
		filename: 'order.csv',
		hasSequence: true,
		sequenceName: 'order_order_id_seq',
		truncate: true,
		excludeColumns: ['order_id'],
	},
	{
		name: 'order_activity',
		filename: 'order_activity.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['order_activity_id'],
	},
	{
		name: 'order_address',
		filename: 'order_address.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['order_address_id'],
	},
	{
		name: 'order_item',
		filename: 'order_item.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['order_item_id'],
	},
	{
		name: 'payment_transaction',
		filename: 'payment_transaction.csv',
		hasSequence: true,
		sequenceName: 'payment_transaction_payment_transaction_id_seq',
		truncate: true,
		excludeColumns: ['payment_transaction_id'],
	},
	{
		name: 'reset_password_token',
		filename: 'reset_password_token.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['reset_password_token_id'],
	},
	{
		name: 'session',
		filename: 'session.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['session_id'],
	},
	{
		name: 'shipment',
		filename: 'shipment.csv',
		hasSequence: true,
		sequenceName: 'shipment_shipment_id_seq',
		truncate: true,
		excludeColumns: ['shipment_id'],
	},
	{
		name: 'shipping_method',
		filename: 'shipping_method.csv',
		hasSequence: true,
		sequenceName: 'shipping_method_shipping_method_id_seq',
		truncate: true,
		excludeColumns: ['shipping_method_id'],
	},
	{
		name: 'shipping_zone',
		filename: 'shipping_zone.csv',
		hasSequence: true,
		sequenceName: 'shipping_zone_shipping_zone_id_seq',
		truncate: true,
		excludeColumns: ['shipping_zone_id'],
	},
	{
		name: 'shipping_zone_method',
		filename: 'shipping_zone_method.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['shipping_zone_method_id'],
	},
	{
		name: 'shipping_zone_province',
		filename: 'shipping_zone_province.csv',
		hasSequence: false,
		truncate: true,
		excludeColumns: ['shipping_zone_province_id'],
	},
	{
		name: 'tax_class',
		filename: 'tax_class.csv',
		hasSequence: true,
		sequenceName: 'tax_class_tax_class_id_seq',
		truncate: true,
		excludeColumns: ['tax_class_id'],
	},
	{
		name: 'tax_rate',
		filename: 'tax_rate.csv',
		hasSequence: true,
		sequenceName: 'tax_rate_tax_rate_id_seq',
		truncate: true,
		excludeColumns: ['tax_rate_id'],
	},
	{
		name: 'url_rewrite',
		filename: 'url_rewrite.csv',
		hasSequence: true,
		sequenceName: 'url_rewrite_url_rewrite_id_seq',
		truncate: true,
		excludeColumns: ['url_rewrite_id'],
	},
	{
		name: 'widget',
		filename: 'widget.csv',
		hasSequence: true,
		sequenceName: 'widget_widget_id_seq',
		truncate: true,
		excludeColumns: ['widget_id'],
	},
]

export default importTables
